// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkotcxcekcsilshbljnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rb3RjeGNla2NzaWxzaGJsam5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTkxMDMsImV4cCI6MjA2MzI5NTEwM30.MttJcvu9jG_4_sF9ry0UzVWPKnddYQdhqlbMG02m12A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);